int gpUpdateKey();
int ScoreShow();
void DataLoad();
void Position();
void PlayerControl();
void pBulletControl();
void pBulletDraw();
void EnemyControl();
void EnemyControl_1();
void EnemyControl_2();
void EnemyControl_3();
void EnemyControl_4();
void eBulletControl();
void eBulletControl_1();
void eBulletControl_2();
void eBulletControl_3();
void eBulletDraw();
void eBulletDraw_1();
void eBulletDraw_2();
void eBulletDraw_3();
void eBulletDraw_4();
void eBulletDraw_5();
void FpsTimeFunction();
void CountFunction(int OldTime);
void ShowMyHp();
int MenuCreate();
static void OpningMusic(int Flg);
static void StageBgm(int flg);
void StageControl();
void ItemControl();